name: ${name}
version: ${version}
main: ${main}
author: ${author}

api-version: ${api_version}

libraries:
  - org.openjdk.nashorn:nashorn-core:15.4
  - org.jsoup:jsoup:1.18.1
  - org.slf4j:slf4j-simple:2.0.16
  - org.slf4j:slf4j-api:2.0.16
  - com.zaxxer:HikariCP:5.1.0
  - org.mariadb.jdbc:mariadb-java-client:3.4.1
  - mysql:mysql-connector-java:8.0.33

commands: